// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return $.ajax({
      url: "http://ip.jsontest.com/"
    }).done(function() {
      return console.log("Success");
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
